on:
  release:
    types: [created]

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    name: Build Docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/386
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
    steps:
      - name: setup qemu
        uses: docker/setup-qemu-action@v3
      - name: setup buildx
        uses: docker/setup-buildx-action@v3
      - name: login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: ${{ matrix.platform }}
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.ref_name }}